# Generated by Django 3.0.8 on 2020-08-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='author',
        ),
    ]
