# Generated by Django 3.0.8 on 2020-08-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200801_0742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCategories',
        ),
    ]
